"use strict";
const CARDS = {
  bomb: {
    name: "炸弹猫",
    short: "抽到就爆炸",
    description: "抽到立即处理。有拆弹可以保命；没有拆弹则出局。不可否定。",
    color: "#FFE3DE",
    symbol: "✹",
    count: 4,
  },
  defuse: {
    name: "拆弹",
    short: "抵消一次爆炸",
    description:
      "仅在抽到炸弹时使用。消耗一张，秘密放回炸弹，结束当前一个回合。不可否定。",
    color: "#DFF1D9",
    symbol: "✂",
    count: 6,
  },
  attack: {
    name: "攻击 ×2",
    short: "下家行动 2 回合",
    description: "不抽牌，把回合交给下家。受攻击时转移剩余回合，再加 2。",
    color: "#FFE3D8",
    symbol: "»",
    count: 4,
  },
  skip: {
    name: "跳过",
    short: "免抽，结束 1 回合",
    description: "不抽牌，结束一个回合。受到攻击时只减少一个剩余回合。",
    color: "#DDF0FF",
    symbol: "↷",
    count: 4,
  },
  favor: {
    name: "索要",
    short: "让对方给你 1 张",
    description: "选择一位有手牌的对手，由对方决定给你哪张。之后仍需继续回合。",
    color: "#FFEAD5",
    symbol: "♡",
    count: 4,
  },
  shuffle: {
    name: "洗牌",
    short: "打乱剩余牌堆",
    description: "重新打乱剩余抽牌堆，不改变任何手牌。不会结束回合。",
    color: "#DCF0EE",
    symbol: "⤨",
    count: 4,
  },
  future: {
    name: "预知 ×3",
    short: "偷看牌顶 3 张",
    description: "仅自己查看牌顶最多三张，顺序不能改变。看完仍需继续回合。",
    color: "#E9E3FA",
    symbol: "◉",
    count: 5,
  },
  nope: {
    name: "否定",
    short: "取消或恢复动作",
    description:
      "在响应窗口内取消待生效动作，也能反否定。不能取消抽牌、炸弹或拆弹。",
    color: "#FFE3EB",
    symbol: "×",
    count: 5,
  },
  cat1: {
    name: "困困猫",
    short: "同名组合偷牌",
    description: "单张无效果。同名两张随机偷一张，同名三张点名索取一张。",
    color: "#EEE8FA",
    symbol: "☾",
    count: 4,
  },
  cat2: {
    name: "饭团猫",
    short: "同名组合偷牌",
    description: "单张无效果。同名两张随机偷一张，同名三张点名索取一张。",
    color: "#FFF0D9",
    symbol: "△",
    count: 4,
  },
  cat3: {
    name: "宇航猫",
    short: "同名组合偷牌",
    description: "单张无效果。同名两张随机偷一张，同名三张点名索取一张。",
    color: "#E4EEFF",
    symbol: "☆",
    count: 4,
  },
  cat4: {
    name: "侦探猫",
    short: "同名组合偷牌",
    description: "单张无效果。同名两张随机偷一张，同名三张点名索取一张。",
    color: "#EEE6DF",
    symbol: "⌕",
    count: 4,
  },
  cat5: {
    name: "摇滚猫",
    short: "同名组合偷牌",
    description: "单张无效果。同名两张随机偷一张，同名三张点名索取一张。",
    color: "#FFE4ED",
    symbol: "♪",
    count: 4,
  },
};
module.exports = { CARDS, TYPES: Object.keys(CARDS) };
